### PR TITLE
#18 Provide tooling for debugging images

### PR DESCRIPTION
**Pull request by ryanemerson**
The additional packages add ~ 4MB to the total image size, well worth it IMO.

### CODE REVIEW

**Comment by ctron** [comment]
I think you need `tar` as well:

Citing from `oc`:
```
  # !!!Important Note!!!
  # Requires that the 'tar' binary is present in your container
  # image.  If 'tar' is not present, 'oc cp' will fail.
```

**Comment by tristantarrant** [comment]
bsdtar Is already there. Maybe a symbolic link?

**Comment by ryanemerson** [comment]
> bsdtar Is already there. Maybe a symbolic link?

Yep looking into that atm. Tar pulls in almost 1 MB by itself, so trying to avoid that if possible.

**Comment by ryanemerson** [comment]
Symlink added and it works with `oc cp` https://github.com/infinispan/infinispan-images/commit/3b7b4af386e4d8335778d56ecf8d9521100f49d2

**Comment by tristantarrant** [comment]
Nice one !

**Pull request merged**
