### PR TITLE
Add xsite

### PR DESCRIPTION
**Pull request by ryanemerson**
```yaml
---
xsite:
  address: 10.3.1.0
  name: LON
  port: 7200
  backups:
    - address: 10.2.1.0
      name: NYC
      port: 7200
```

When the above yaml is present in the configuration yaml, the following happens:

1.  A `relay-global.xml` file that contains:
    - TCP with `bind_addr` and `bind_port` set to the local sites configured `xsite.address` and `xsite.port`
    - TCPPING with `initial_hosts` set to a csv list of `port[address]` containing the local site and all backups
2. A `<stack-file name="relay-global" path="jgroups-relay.xml"/>` entry in `infinispan.xml` to load the stack when xsite backups are specified, otherwise ignored.
3. `<transport site="${xsite.name}"/>`
4. The relay protocol is added to the TCP stack in this form:
```xml
  <relay site='LON'>
    <remote-site name='NYC' stack='relay-global' cluster='global'/>
    <property name='relay_multicasts'>
      false
    </property>
    <property name='max_site_masters'>
      1000
    </property>
  </relay>
```

@galderz Am I missing anything? I don't have a way to test Xsite.

I took the `relay_multicasts` and `max_site_masters` properties from the quickstart. Are these required or desired?

Do we want to allow Xsite with a local UDP stack or just TCP?

### CODE REVIEW

**Comment by pruivo** [comment]
@ryanemerson 
`relay_multicasts` is no longer needed. We are setting the JG `NO_RELAY` flag for multicasts
`max_site_masters` is an optimization configuration. if `==1`, all nodes in the local cluster will forward the request to the same node (you will have 1 extra hop for each xsite request).
The optimal value should be `> num-nodes` in the cluster (i.e. each node reaches the remote site directly)

**Comment by ryanemerson** [comment]
@pruivo Ok, so do you think users should be able to configure `max_site_masters` or is setting it to a very large value such as `1000` sufficient? Is there any disadvantage to setting it to a value which is much greater than the cluster size?

**Comment by pruivo** [comment]
@ryanemerson I'm not aware of any disadvantage/penalties by setting `max_site_masters >> num_nodes`. 
The only drawback of having `max_site_masters > 1` is the view size on the bridge cluster (and the  view change trigger when any node in the sites joins or leaves)

I would let the users configure it but, if possible, set a higher value as default. (~100. I doubt there are clusters larger than that)

**Comment by pruivo** [comment]
@ryanemerson I didn't check your changes, but there is another property that may be useful to configure: `can_become_site_master` (default `true`).
If a node doesn't have access to the remote site, must set this to `false`

**Comment by pruivo** [comment]
@ryanemerson one final thing, `<transport site="${xsite.name}"/>` is not related to xsite neither RELAY configuration.
This is used with `machine_id` and `rack_id` to configure the topology-aware consistent hash.
The `site` value can be different from the `RELAY.site`

**Comment by ryanemerson** [comment]
@pruivo Thanks for all the feedback, very helpful :slightly_smiling_face:

**Comment by galderz** [comment]
@ryanemerson 

> TCP with bind_addr and bind_port set to the local sites configured xsite.address and xsite.port

I don't think that's right. `xsite.address` and `xsite.port` should set `TCP.external_addr` and `TCP.external_port`. See [here](https://github.com/jboss-developer/jboss-jdg-quickstarts/blob/jdg-7.3.x/openshift/datagrid-service/xsite/configuration/standalone.xml#L239).

**Comment by ryanemerson** [comment]
> @ryanemerson I didn't check your changes, but there is another property that may be useful to configure: `can_become_site_master` (default `true`).
> If a node doesn't have access to the remote site, must set this to `false`

@galderz Any thoughts on this? Do we just assume that all pod's in a site have access to the external site?

I could expose this as:
```yaml
---
xsite:
   masterCandidate: true|false
```

With the default being true if not specified.

**Comment by ryanemerson** [comment]
I added the `masterCandidate` option and pushed: https://github.com/infinispan/infinispan-images/commit/bd3656c2ce5409d7f105b71024b4dbe69e122b73

**Comment by galderz** [comment]
@ryanemerson Pod-specific configuration that affects only certain pods would be very hard to maintain. So, I'd leave such option out for now.

**Comment by ryanemerson** [comment]
@galderz I merged this 5 days ago :see_no_evil:. The code to add/remove the property is minimal, so I will leave it in for now.

**Pull request closed without merging**
